### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by han1548772930** [yigehaobb/vue-vben-admin-tauri#1]
ailed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/config-provider/style/index" from "src\App.vue". Does the file exist?

 ERROR  14:18:56 [vite] Internal server error: Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/config-provider/style/index" from "src\App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/src/App.vue
  1  |  import { defineComponent as _defineComponent } from "vue";
  2  |  import { ConfigProvider } from "ant-design-vue";
  3  |  import 'E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/config-provider/style/index';
     |          ^
  4  |  
  5  |  import { AppProvider } from "/@/components/Application";
      at formatError (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39080:46)
      at TransformContext.error (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39076:19)
      at normalizeUrl (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58360:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58509:57)
      at async Object.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39317:30)
      at async doTransform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:50043:29)

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/input/style/index" from "src\components\registerGlobComp.ts". Does the file exist?

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\router\guard\index.ts". Does the file exist?

 ERROR  14:18:56 [vite] Internal server error: Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\router\guard\index.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/src/router/guard/index.ts
  4  |  import { AxiosCanceler } from "/@/utils/http/axios/axiosCancel";
  5  |  import { Modal, notification } from "ant-design-vue";
  6  |  import 'E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index';
     |          ^
  7  |  import 'E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/notification/style/index';
  8  |  
      at formatError (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39080:46)
      at TransformContext.error (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39076:19)
      at normalizeUrl (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58360:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58509:57)
      at async Object.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39317:30)
      at async doTransform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:50043:29)

 ERROR  14:18:57 [vite] Internal server error: Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/input/style/index" from "src\components\registerGlobComp.ts". Does the file exist?
  Plugin: vite:import-analysis
  File: E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/src/components/registerGlobComp.ts
  1  |  import { Button } from "./Button";
  2  |  import { Input, Layout } from "ant-design-vue";
  3  |  import 'E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/input/style/index';
     |          ^
  4  |  import 'E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/layout/style/index';
  5  |  
      at formatError (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39080:46)
      at TransformContext.error (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39076:19)
      at normalizeUrl (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58360:26)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:58509:57)
      at async Object.transform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:39317:30)
      at async doTransform (E:\desk\vue-vben-admin-tauri-main\vue-vben-admin-tauri-main\node_modules\_vite@2.9.15@vite\dist\node\chunks\dep-689425f3.js:50043:29)

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/spin/style/index" from "src\components\Loading\src\Loading.vue". Does the file exist?

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\hooks\web\useMessage.tsx". Does 
the file exist?

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\hooks\web\useMessage.tsx". Does 
the file exist? (x2)

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/spin/style/index" from "src\components\Loading\src\Loading.vue". Does the file exist?

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\hooks\web\useMessage.tsx". Does 
the file exist?

 ERROR  Failed to resolve import "E:/desk/vue-vben-admin-tauri-main/vue-vben-admin-tauri-main/node_modules/_ant-design-vue@3.2.13@/ant-design-vue/es/modal/style/index" from "src\hooks\web\useMessage.tsx". Does 
the file exist? (x2)

**Comment by han1548772930** [comment]
我用pnpm重新下载一下可以了
